name: Duplex
options:
    bundleIdPrefix: com.duplex
    deploymentTarget:
        tvOS: "17.0"
settings:
    SERVER_URL: http://localhost:2345
targets:
    Duplex:
        type: application
        platform: tvOS
        sources:
            - Sources
        settings:
            INFOPLIST_FILE: Sources/Info.plist
            DEVELOPMENT_TEAM: $(DEVELOPMENT_TEAM)
            PRODUCT_BUNDLE_IDENTIFIER: com.duplex.app
            CODE_SIGN_STYLE: Automatic
            ASSETCATALOG_COMPILER_APPICON_NAME: "App Icon & Top Shelf Image"
